name: Workflow for Ubiquidity

on:
  push:
    branches:
      - main
      - development
      - staging
      - production
  pull_request:
    branches:
      - main
      - development
      - staging
      - production
  create:
    tag:
      - "v*"

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Setup environment
        run: yarn install:env

      - name: Install contracts
        run: yarn install:contracts

      - name: Build contracts
        run: yarn build:contracts

      - name: Installing UI
        run: yarn install

      - name: Building UI
        run: yarn BUILD:NEXT
