name: Workflow for Ubiquidity

on:
  push:
    branches:
      - main
      - development
      - staging
      - production
  pull_request:
    branches:
      - main
      - development
      - staging
      - production
  create:
    tag:
      - "v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: sudo apt -y install libusb-1.0-0-dev libudev-dev

      - name: Yarn install
        run: yarn install

      - name: Setup environment
        run: yarn install:env

      - name: Install contracts
        run: yarn install:contracts

      - name: Build contracts
        run: yarn build:contracts

      - name: Building UI
        run: yarn BUILD:NEXT

      # - name: Yarn test
      #   run: yarn test:all

      - name: Deploy Development
        if: github.ref == 'refs/heads/development'
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
          netlify deploy --prod --build

      - name: Deploy Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
          netlify deploy --prod --build

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
          netlify deploy --prod --build
