name: Receive workflow and Deploy

on:
  workflow_run:
    workflows: ["Install and Build Workflow"]
    types:
      - completed

jobs:
  receive-pr-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Download artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const download_artifact = require('./download_artifact.js');
            download_artifact(github, context)
      - name: Extract files
        run: unzip pr.zip && unzip pull-request.zip && ls

      - name: Deploy Development
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --prod > ./deployments.log

      - name: Print Logs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const https = require('https');
            const pr_info = fs.readFileSync('./pr_number').toString('utf-8');
            console.log({pr_info});
            const substrs = pr_info.split(',');
            const event_name = substrs[0].split('=')[1];
            const pr_number = substrs[1].split('=')[1] ?? 0;
            const commit_sha = substrs[2].split('=')[1];
            const deployments_log = fs.readFileSync('./deployments.log').toString('utf-8');

            if (event_name == 'pull_request') {
              console.log("Creating a comment for the pull request");
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: deployments_log
              });
            } else {
              console.log("Creating a comment for the commit");
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commit_sha,
                body: deployments_log
              });
            }
